from __future__ import annotations

# Group -> selectable clubs. Used for button-based selection (no typing).
CLUB_GROUPS: dict[str, tuple[str, ...]] = {
    "SMUSA": (
        "SMUSA - SMU Students' Association",
        "The Blue and Gold (SMUSA)",
    ),
    "ACF": (
        "SMU Arts and Cultural Fraternity (ACF)",
        "SMU Ambassadorial Corps",
        "SMU Ardiente",
        "SMU Artdicted",
        "SMU Ballare",
        "SMU Broadcast and Entertainment (SMUBE)",
        "SMU Caderas Latinas",
        "SMU Chamber Choir",
        "SMU Chinese Orchestra",
        "SMU Eurhythmix",
        "SMU Funk Movement",
        "SMU Guitarissimo",
        "SMU Indancity",
        "SMU Ivory Keys",
        "SMU Literati",
        "SMU Malay Language & Cultural Club",
        "SMU Samba Masala",
        "SMU SoundFoundry",
        "SMU Stageit",
        "SMU Stereometa",
        "SMU Symphonia",
        "SMU VOIX",
        "SMUSAIC",
    ),
    "SICS": (
        "Special Interest & Community Service Sodality",
        "SMU AIESEC",
        "SMU Barworks",
        "SMU Caretalyst",
        "SMU Debating Society (SMUDS)",
        "SMU Ember",
        "SMU eSports",
        "SMU Fitnessworks",
        "SMU Gourmet Club",
        "SMU iSports",
        "SMU People for Animal Welfare",
        "SMU Recreational Fishing Club",
        "SMU Red Cross",
        "SMU Rotaract",
        "SMU Start Up Society",
        "SMU Strategica",
        "SMU Thrive Social Consulting",
        "SMU Toastmasters Club",
        "SMU Uni-Y",
        "SMU Verts",
        "SMU Wine Appreciation Club",
        "SMU Women's Connection (SWC)",
        "SMU Youth Mentors",
    ),
    "SSU": (
        "SSU - SMU Sports Union",
        "SMU Aikido Club",
        "SMU Aquathlon",
        "SMU Aquatic Sharks",
        "SMU Archery",
        "SMU Athletics",
        "SMU Badminton",
        "SMU Basketball",
        "SMU Bowling",
        "SMU Climb Team",
        "SMU Cuesports",
        "SMU Dragonboat",
        "SMU Fencing",
        "SMU Floorball Club",
        "SMU Football",
        "SMU Golf",
        "SMU Handball",
        "SMU Judo",
        "SMU Kendo Club",
        "SMU Mixed Martial Arts Club",
        "SMU Muay Thai",
        "SMU Netball",
        "SMU Rugby",
        "SMU Sailing",
        "SMU Softball",
        "SMU Squash",
        "SMU Table Tennis",
        "SMU Taekwondo",
        "SMU Tchoukball",
        "SMU Tennis",
        "SMU Ultimate Frisbee Club",
        "SMU Volleyball",
        "SMU Wushu",
    ),
    "SMUX": (
        "SMUXploration Crew",
        "SMUX Biking",
        "SMUX Diving",
        "SMUX Kayaking",
        "SMUX Skating",
        "SMUX Trekking",
        "SMUX Xseed",
    ),
    "ROS": (
        "SMU Apolitical",
        "SMU Cru",
        "SMU Christian Fellowship",
        "SMU Catholic Community (FIDES)",
        "SMU Muslim Society",
        "SMU Dhamma Circle",
        "SMU Sikh Society",
    ),
    "School of Social Sciences": (
        "SOSCIETY, SMU Social Sciences Society",
        "SMU Psychology Society",
    ),
    "Yong Pung How School of Law": (
        "The Bar, SMU Law Society",
        "SMU Law Sports and Recreation Club (SPARC)",
        "SMU Law International Relations Club (IRC)",
        "Moot Court Club",
        "Lexicon: An SMU Law Student Publication",
        "SMU Legal Innovation and Technology (LIT)",
        "SMU Corporate & Commercial Club (COCO)",
        "SMU Constitutional Law & Criminal Justice Club",
        "SMU Law Outreach Club (PKA Pro Bono Club)",
        "SMU Mediation and Negotiation Club (SMNC)",
        "Student Chapter of the International Law Association (SILA)",
    ),
    "School of Computing and Information Systems": (
        "Ellipsis, SMU Information Systems Society",
        "SMU Whitehat Society",
        "SMU .Hack",
        "SMU-ISACA Student Chapter",
        "SMU Product Club",
        "SMU Women in Tech",
    ),
    "School of Economics": (
        "SMU Actuarial Science Club",
        "SMU Data Science and Analytics Society (DSA)",
        "SMU Health Economics and Management (HEM) Society",
        "OIKOS, SMU Economics Society",
        "SMU Economics Intelligence Club",
    ),
    "School of Accountancy": (
        "Asoc, Accounting Society",
        "SMU Emerging Markets",
        "SOA Outreach",
        "Tax Society@SMU",
    ),
    "Lee Kong Chian School of Business": (
        "BONDUE, SMU Business Society",
        "SMU Marketing Society (Smarketing)",
        "SMU Organisational Behaviour & Human Resources Society",
        "SMU Quantitive Finance Society (Q.E.D)",
        "SMU Cognitare",
        "SMU EYE Investment Club",
        "SMU Student-Managed Investment Fund (SMIF)",
        "SMU Operations Management Society (OMS)",
        "SMU Communication Management Society (CMS)",
        "SMU Real Estate & Alternative Investments (SMUREAL)",
    ),
    "College of Integrative Studies": ("inCISive",),
    "Offices / Institutes / Centres": (
        "International Connections (ICON)",
        "ICON - SMU Al Khaleej",
        "ICON - SMU Truly Malaysia (SMUTM)",
        "ICON - SMU Japanese Cultural Club (JCC)",
        "ICON - SMU Connect China",
        "ICON - SMU Chao Vietnam",
        "ICON - SMU Francophiles",
        "ICON - SMU Barkada",
        "ICON - SMU Woori Sayi",
        "ICON - SMU Yim Siam Club",
        "ICON - SMU Apsara Cambodia",
        "ICON - SMU Roots (Singaporean Cultural Club)",
        "ICON - SMU Myanmar Community (SMUMC)",
        "ICON - SMU Indian Cultural Society (ICS)",
        "ICON - SMU Komunitas Indonesia (SMUKI)",
        "SMU Purple",
        "The Mentoring Circle",
        "Residents' Seniors (SMU Prinsep Street Residences)",
        "SMU Peer Helpers",
        "SMU Student Council of Discipline (SCD)",
        "SMU Financial Advisory and Compliance Team (FACT)",
        "Singapore Mentorship Committee (SMU-SMC)",
        "Growth-X Consulting",
        "SMU Civil Defence Lionhearter Chapter",
        "Asia Private Equity Club @ SMU (APECS)",
        "SMU Blockchain Club",
        "SMU FinTech Club",
        "SMU Artificial Intelligence Club",
        "SMU Business Intelligence & Analytics (BIA)",
        "SMU Smart City Society",
        "SMU Eagles Inc.",
        "SMU Sustainable Investment Club",
        "SMU Maritime Merchants Society",
        "SMU FinLIT Programme",
        "Avente Consulting",
        "SMU Social Impact Catalyst (SIC)",
        "SMU Re-X",
        "SMU Career Champions",
        "SMU YTSG Student Chapter",
    ),
}

